# Generated by Django 5.1.15 on 2026-07-12 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="automationrun",
            new_name="automations_organiz_06b996_idx",
            old_name="automations_organiz_8a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="automationrun",
            new_name="automations_workflo_f9e1c7_idx",
            old_name="automations_workflo_9d3e4f_idx",
        ),
    ]
