# Generated by Django 5.1.15 on 2026-07-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "automations",
            "0002_rename_automations_organiz_8a1b2c_idx_automations_organiz_06b996_idx_and_more",
        ),
        ("workflows", "0003_phase11_18"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrun",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_runs",
                to="workflows.workflow",
            ),
        ),
    ]
