# Generated by Django 5.1.15 on 2026-07-12 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_invite"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invite",
            new_name="organizatio_organiz_a8ab14_idx",
            old_name="organizatio_organiz_7f2a1c_idx",
        ),
    ]
