# Generated by Django 5.1.15 on 2026-07-12 18:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "organizations",
            "0003_rename_organizatio_organiz_7f2a1c_idx_organizatio_organiz_a8ab14_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField()),
                ("secret", models.CharField(blank=True, default="", max_length=255)),
                ("events", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "developer_webhook_endpoint",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event", models.CharField(max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("response_code", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, default="")),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="developer.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "developer_webhook_delivery",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("prefix", models.CharField(db_index=True, max_length=16)),
                ("hashed_key", models.CharField(max_length=128)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "developer_api_key",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "prefix"], name="developer_a_organiz_1f53e2_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["organization", "is_active"], name="developer_w_organiz_0110c6_idx"
            ),
        ),
    ]
