# Generated by Django 5.1.15 on 2026-07-12 17:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "organizations",
            "0003_rename_organizatio_organiz_7f2a1c_idx_organizatio_organiz_a8ab14_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="documents/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "DOCX"),
                            ("pptx", "PPTX"),
                            ("xlsx", "XLSX"),
                            ("csv", "CSV"),
                            ("image", "Image"),
                            ("text", "Text"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=16,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_studio_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studio_documents",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "documents_studio_document",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("analyze", "Analyze"),
                            ("summarize", "Summarize"),
                            ("translate", "Translate"),
                            ("compare", "Compare"),
                            ("extract", "Extract"),
                            ("ocr", "OCR"),
                            ("search", "Search"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="documents.studiodocument",
                    ),
                ),
            ],
            options={
                "db_table": "documents_job",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="studiodocument",
            index=models.Index(
                fields=["organization", "status"], name="documents_s_organiz_2bc153_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentjob",
            index=models.Index(
                fields=["document", "status"], name="documents_j_documen_a94074_idx"
            ),
        ),
    ]
