# Generated by Django 5.1.15 on 2026-07-12 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="assistant_c_organiz_a0c814_idx",
            old_name="assistant_c_organiz_a1b2c3_idx",
        ),
    ]
