export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login/",
    register: "/auth/register/",
    logout: "/auth/logout/",
    refresh: "/auth/refresh/",
    me: "/auth/me/",
    forgotPassword: "/auth/forgot-password/",
    resetPassword: "/auth/reset-password/",
    verifyEmail: "/auth/email/verify/",
    emailVerify: "/auth/email/verify/",
    emailResend: "/auth/email/resend/",
    twoFactor: "/auth/2fa/verify/",
    twoFactorSetup: "/auth/2fa/setup/",
    twoFactorConfirm: "/auth/2fa/confirm/",
    twoFactorDisable: "/auth/2fa/disable/",
    twoFactorEnable: "/auth/2fa/setup/",
    sessions: "/auth/sessions/",
    revokeSession: (id: string) => `/auth/sessions/${id}/`,
    socialGoogle: "/auth/social/google/",
    socialGithub: "/auth/social/github/",
  },
  organizations: {
    list: "/organizations/",
    detail: (id: string) => `/organizations/${id}/`,
    create: "/organizations/",
    update: (id: string) => `/organizations/${id}/`,
    delete: (id: string) => `/organizations/${id}/`,
    members: (id: string) => `/organizations/${id}/memberships/`,
    memberships: (id: string) => `/organizations/${id}/memberships/`,
    membershipDetail: (orgId: string, membershipId: string) =>
      `/organizations/${orgId}/memberships/${membershipId}/`,
  },
  workflows: {
    list: "/workflows/",
    detail: (id: string) => `/workflows/${id}/`,
    create: "/workflows/",
    update: (id: string) => `/workflows/${id}/`,
    delete: (id: string) => `/workflows/${id}/`,
    run: (id: string) => `/workflows/${id}/run/`,
    validate: (id: string) => `/workflows/${id}/validate/`,
    publish: (id: string) => `/workflows/${id}/publish/`,
    nodeTypes: "/workflows/node-types/",
    runs: (id: string) => `/workflows/${id}/runs/`,
    definition: (id: string) => `/workflows/${id}/definition/`,
  },
  automations: {
    list: "/automations/",
    detail: (id: string) => `/automations/${id}/`,
    create: "/automations/",
    update: (id: string) => `/automations/${id}/`,
    delete: (id: string) => `/automations/${id}/`,
    toggle: (id: string) => `/automations/${id}/toggle/`,
    trigger: "/automations/trigger/",
  },
  dashboard: {
    overview: "/dashboard/overview/",
    stats: "/dashboard/stats/",
    activity: "/dashboard/activity/",
    usage: "/dashboard/usage/",
  },
  notifications: {
    list: "/notifications/",
    markRead: (id: string) => `/notifications/${id}/read/`,
    markAllRead: "/notifications/read-all/",
  },
  assistant: {
    conversations: "/assistant/conversations/",
    conversation: (id: string) => `/assistant/conversations/${id}/`,
    messages: (id: string) => `/assistant/conversations/${id}/messages/`,
    messagesStream: (id: string) => `/assistant/conversations/${id}/messages/stream/`,
    uploads: "/assistant/uploads/",
  },
  settings: {
    profile: "/settings/profile/",
    preferences: "/settings/preferences/",
  },
  knowledge: {
    documents: "/knowledge/documents/",
    document: (id: string) => `/knowledge/documents/${id}/`,
    upload: "/knowledge/documents/",
    reprocess: (id: string) => `/knowledge/documents/${id}/reprocess/`,
    chunks: (id: string) => `/knowledge/documents/${id}/chunks/`,
    conversations: "/knowledge/conversations/",
    conversation: (id: string) => `/knowledge/conversations/${id}/`,
    messages: (id: string) => `/knowledge/conversations/${id}/messages/`,
  },
  crm: {
    companies: "/crm/companies/",
    company: (id: string) => `/crm/companies/${id}/`,
    contacts: "/crm/contacts/",
    contact: (id: string) => `/crm/contacts/${id}/`,
    leads: "/crm/leads/",
    lead: (id: string) => `/crm/leads/${id}/`,
    convertLead: (id: string) => `/crm/leads/${id}/convert/`,
    opportunities: "/crm/opportunities/",
    opportunity: (id: string) => `/crm/opportunities/${id}/`,
    pipeline: "/crm/pipeline/",
    notes: "/crm/notes/",
    note: (id: string) => `/crm/notes/${id}/`,
    activities: "/crm/activities/",
    activity: (id: string) => `/crm/activities/${id}/`,
    followUp: (id: string) => `/crm/activities/${id}/ai-follow-up/`,
  },
  support: {
    channels: "/support/channels/",
    channel: (id: string) => `/support/channels/${id}/`,
    tickets: "/support/tickets/",
    ticket: (id: string) => `/support/tickets/${id}/`,
    messages: (ticketId: string) => `/support/tickets/${ticketId}/messages/`,
    reply: (ticketId: string) => `/support/tickets/${ticketId}/messages/`,
    aiReply: (ticketId: string) => `/support/tickets/${ticketId}/ai-reply/`,
    assign: (ticketId: string) => `/support/tickets/${ticketId}/assign/`,
    stats: "/support/stats/",
  },
  marketing: {
    generate: "/marketing/generate/",
    assets: "/marketing/assets/",
    asset: (id: string) => `/marketing/assets/${id}/`,
    improve: (id: string) => `/marketing/assets/${id}/improve/`,
    campaigns: "/marketing/campaigns/",
    campaign: (id: string) => `/marketing/campaigns/${id}/`,
  },
  documents: {
    list: "/documents/",
    detail: (id: string) => `/documents/${id}/`,
    upload: "/documents/",
    jobs: (id: string) => `/documents/${id}/jobs/`,
    job: (id: string) => `/documents/jobs/${id}/`,
  },
  reports: {
    list: "/reports/",
    create: "/reports/",
    templates: "/reports/templates/",
    generate: "/reports/generate/",
    detail: (id: string) => `/reports/${id}/`,
  },
  meetings: {
    list: "/meetings/",
    detail: (id: string) => `/meetings/${id}/`,
    create: "/meetings/",
    update: (id: string) => `/meetings/${id}/`,
    delete: (id: string) => `/meetings/${id}/`,
    createLink: (id: string) => `/meetings/${id}/create-link/`,
    connections: "/meetings/calendar/connections/",
    connect: (provider: string) => `/meetings/calendar/connect/${provider}/`,
    calendarCallback: "/meetings/calendar/callback/",
    bookingLinks: "/meetings/booking-links/",
    bookingLink: (id: string) => `/meetings/booking-links/${id}/`,
    publicBooking: (slug: string) => `/meetings/booking/${slug}/`,
    reminders: (meetingId: string) => `/meetings/${meetingId}/reminders/`,
  },
  agents: {
    catalog: "/agents/catalog/",
    list: "/agents/",
    detail: (id: string) => `/agents/${id}/`,
    create: "/agents/",
    update: (id: string) => `/agents/${id}/`,
    delete: (id: string) => `/agents/${id}/`,
    run: (id: string) => `/agents/${id}/run/`,
    runs: (id: string) => `/agents/${id}/runs/`,
  },
  billing: {
    plans: "/billing/plans/",
    subscription: "/billing/subscription/",
    checkout: "/billing/checkout/",
    portal: "/billing/portal/",
    invoices: "/billing/invoices/",
    usage: "/billing/usage/",
    coupon: "/billing/coupons/validate/",
    refunds: "/billing/refunds/",
  },
  analytics: {
    overview: "/analytics/overview/",
    revenue: "/analytics/revenue/",
    mrr: "/analytics/mrr/",
    arr: "/analytics/arr/",
    retention: "/analytics/retention/",
    churn: "/analytics/churn/",
    aiUsage: "/analytics/ai-usage/",
    performance: "/analytics/performance/",
    satisfaction: "/analytics/satisfaction/",
  },
  admin: {
    users: "/admin/users/",
    user: (id: string) => `/admin/users/${id}/`,
    organizations: "/admin/organizations/",
    subscriptions: "/admin/subscriptions/",
    payments: "/admin/payments/",
    analyticsOverview: "/admin/analytics/overview/",
    aiUsage: "/admin/ai-usage/",
    auditLogs: "/admin/audit-logs/",
    settings: "/admin/settings/",
  },
  security: {
    status: "/security/status/",
    auditLogs: "/security/audit-logs/",
    backup: "/security/backups/",
  },
  apiKeys: {
    list: "/api-keys/",
    create: "/api-keys/",
    detail: (id: string) => `/api-keys/${id}/`,
    revoke: (id: string) => `/api-keys/${id}/`,
  },
  webhooks: {
    list: "/webhooks/",
    create: "/webhooks/",
    detail: (id: string) => `/webhooks/${id}/`,
    update: (id: string) => `/webhooks/${id}/`,
    delete: (id: string) => `/webhooks/${id}/`,
  },
  health: "/health/",
  ai: {
    documents: "/ai/documents/",
    documentsSearch: "/ai/documents/search/",
    document: (id: string) => `/ai/documents/${id}/`,
  },
} as const;
