# Generated by Django 5.1.15 on 2026-07-12 17:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "organizations",
            "0003_rename_organizatio_organiz_7f2a1c_idx_organizatio_organiz_a8ab14_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("sales", "Sales"),
                            ("hr", "HR"),
                            ("marketing", "Marketing"),
                            ("inventory", "Inventory"),
                            ("executive", "Executive"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="weekly",
                        max_length=16,
                    ),
                ),
                ("cron_expression", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "reports_schedule",
                "ordering": ("report_type",),
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("sales", "Sales"),
                            ("hr", "HR"),
                            ("marketing", "Marketing"),
                            ("inventory", "Inventory"),
                            ("executive", "Executive"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("content", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "reports_report",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "type", "status"],
                        name="reports_rep_organiz_9bbef3_idx",
                    )
                ],
            },
        ),
    ]
