# Generated by Django 5.1.15 on 2026-07-12 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiusagerecord",
            new_name="dashboard_a_organiz_1d08bd_idx",
            old_name="dashboard_a_organiz_c1d2e3_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="dashboard_n_user_id_b5486f_idx",
            old_name="dashboard_n_user_id_b8f0a1_idx",
        ),
    ]
