# Generated by Django 5.1.15 on 2026-07-12 18:02

from django.db import migrations

import infrastructure.vector.fields


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgechunk",
            name="embedding",
            field=infrastructure.vector.fields.EmbeddingField(blank=True, null=True),
        ),
    ]
