# Generated by Django 5.1.15 on 2026-07-12 17:33

from django.db import migrations

import apps.ai_engine.infrastructure.models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="document",
            new_name="ai_engine_d_organiz_1bf5d9_idx",
            old_name="ai_engine_d_organiz_a1b2c3_idx",
        ),
        migrations.AlterField(
            model_name="document",
            name="embedding",
            field=apps.ai_engine.infrastructure.models.EmbeddingField(blank=True, null=True),
        ),
    ]
