import type { ModuleGuide } from "@/features/guides/types";

const routeGuide = (
  id: string,
  route: string,
  title: string,
  purpose: string,
  firstAction: string,
  outcome: string,
): ModuleGuide => ({
  id,
  version: 1,
  title,
  match: (pathname) => pathname === route,
  steps: [
    {
      target: "[data-guide='module-root']",
      title: `Welcome to ${title}`,
      body: purpose,
    },
    {
      target: "main button, main a",
      title: "Start here",
      body: firstAction,
    },
    {
      target: "[data-guide='module-help']",
      title: "Get the best result",
      body: `${outcome} You can restart this guide from Help at any time.`,
    },
  ],
});

export const GUIDE_REGISTRY: ModuleGuide[] = [
  {
    id: "workflow-builder",
    version: 1,
    title: "Workflow Builder",
    match: (pathname) => /^\/workflows\/[^/]+\/builder\/?$/.test(pathname),
    steps: [
      {
        target: "[data-guide='module-root']",
        title: "Build the process visually",
        body: "Add a trigger, connect action nodes, and configure each node with the real business process you want Novixa to run.",
      },
      {
        target: "main button",
        title: "Validate before publishing",
        body: "Save and validate the workflow, then run a test with realistic input before activating it.",
      },
      {
        target: "[data-guide='module-help']",
        title: "Improve over time",
        body: "Review run results in Automations and refine prompts or conditions. Restart this guide from Help.",
      },
    ],
  },
  routeGuide(
    "dashboard",
    "/dashboard",
    "Dashboard",
    "Use this overview to monitor active workflows, running automations, recent activity, and business outcomes.",
    "Open a quick-start action or choose a module from the sidebar.",
    "Check this page daily for failures, usage changes, and work that needs attention.",
  ),
  routeGuide(
    "assistant",
    "/assistant",
    "Assistant",
    "Ask questions or request work using the business profile and knowledge your organization has provided.",
    "Create a conversation and describe the result, audience, constraints, and deadline.",
    "Attach relevant files and review citations before using important output.",
  ),
  routeGuide(
    "workflows",
    "/workflows",
    "Workflows",
    "Design repeatable business processes as connected triggers, decisions, AI steps, and actions.",
    "Create a workflow from one clear process, then open its visual builder.",
    "Test with real examples before activating and keep each workflow focused on one outcome.",
  ),
  routeGuide(
    "automations",
    "/automations",
    "Automations",
    "Monitor scheduled and event-driven workflow execution in real time.",
    "Open Configure to edit the linked workflow or inspect a recent run.",
    "Resolve failed runs first, then use successful run data to improve the workflow.",
  ),
  routeGuide(
    "knowledge",
    "/knowledge",
    "Knowledge",
    "Upload trusted business documents so AI answers and agents can use organization-specific facts.",
    "Upload a focused, current document and wait until its status becomes Ready.",
    "Replace outdated files and ask questions that reference the source material.",
  ),
  routeGuide(
    "crm",
    "/crm",
    "CRM",
    "Manage companies, contacts, leads, opportunities, follow-ups, and pipeline activity.",
    "Add a company or lead, then move qualified work through the pipeline.",
    "Keep records complete so AI follow-ups and reports remain accurate.",
  ),
  routeGuide(
    "support",
    "/support",
    "Support",
    "Handle customer conversations from connected channels and use AI to draft context-aware replies.",
    "Select a ticket, review its history, then draft or send a reply.",
    "Verify AI drafts before sending and track response and resolution times.",
  ),
  routeGuide(
    "marketing",
    "/marketing",
    "Marketing",
    "Create content, connect social accounts, publish campaigns, and track Facebook/WhatsApp activity.",
    "Connect a channel or generate an asset using a clear offer and target audience.",
    "Use your saved brand voice and review live-provider status before publishing.",
  ),
  routeGuide(
    "documents",
    "/documents",
    "Documents",
    "Upload documents for analysis, summaries, translation, comparison, extraction, OCR, and Q&A.",
    "Upload one document and choose the action that matches your desired output.",
    "Include a precise question and verify extracted dates, amounts, and legal details.",
  ),
  routeGuide(
    "reports",
    "/reports",
    "Reports",
    "Generate operational and executive narratives from live organization data.",
    "Choose a report type and a meaningful reporting period.",
    "Review source metrics and recommendations before sharing the report.",
  ),
  routeGuide(
    "meetings",
    "/meetings",
    "Meetings",
    "Schedule meetings, create join links, connect calendars, and manage booking links and reminders.",
    "Create a meeting with the correct provider, timezone, attendees, and duration.",
    "Connect a live calendar provider before relying on external event synchronization.",
  ),
  routeGuide(
    "agents",
    "/agents",
    "AI Agents",
    "Run specialist agents that use your business profile and configured playbooks.",
    "Choose the agent closest to the task and give it a measurable goal plus constraints.",
    "Review run history, tune instructions, and only enable tools the agent needs.",
  ),
  routeGuide(
    "billing",
    "/billing",
    "Billing",
    "Manage your plan, 15-day trial, card, invoices, usage, and manual payment requests.",
    "Confirm the selected plan, card status, auto-charge setting, and trial end date.",
    "Monitor usage and update payment details before renewal to prevent interruption.",
  ),
  routeGuide(
    "analytics",
    "/analytics",
    "Analytics",
    "Track revenue, retention, AI usage, churn, and operational trends.",
    "Select the relevant period and compare changes rather than isolated totals.",
    "Turn meaningful trends into a workflow, campaign, or follow-up action.",
  ),
  routeGuide(
    "security",
    "/security",
    "Security",
    "Review security status, backups, sessions, and audit activity.",
    "Resolve high-priority findings and confirm backups are current.",
    "Enable 2FA in Settings and review sessions and audit logs regularly.",
  ),
  routeGuide(
    "developer",
    "/developer",
    "Developer",
    "Create API credentials, configure webhooks, and integrate external systems.",
    "Create the minimum-scope credential and copy it once to a secret manager.",
    "Verify webhook signatures, rotate keys, and never expose secrets in frontend code.",
  ),
  routeGuide(
    "settings",
    "/settings",
    "Settings",
    "Maintain your identity, security, preferences, and the business context shared by AI features.",
    "Keep the business description, customers, goals, brand voice, and logo current.",
    "Changes affect AI output across the whole workspace, so save accurate details.",
  ),
  routeGuide(
    "admin",
    "/admin",
    "Platform Admin",
    "Manage users, organizations, subscriptions, payments, AI usage, and audit events.",
    "Review exceptions and pending payments before changing platform-wide settings.",
    "Use least privilege and audit every sensitive administrative action.",
  ),
];

export function findGuide(pathname: string): ModuleGuide | null {
  return GUIDE_REGISTRY.find((guide) => guide.match(pathname)) ?? null;
}
