# Generated by Django 5.1.15 on 2026-07-12 17:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "organizations",
            "0003_rename_organizatio_organiz_7f2a1c_idx_organizatio_organiz_a8ab14_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("shortcut", models.CharField(blank=True, default="", max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "support_canned_response",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="SupportChannel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("whatsapp", "WhatsApp"),
                            ("messenger", "Messenger"),
                            ("telegram", "Telegram"),
                            ("instagram", "Instagram"),
                            ("email", "Email"),
                            ("live_chat", "Live Chat"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_channels",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "support_channel",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("requester_email", models.EmailField(blank=True, default="", max_length=254)),
                ("requester_name", models.CharField(blank=True, default="", max_length=255)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="support.supportchannel",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "support_ticket",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("agent", "Agent"),
                            ("ai", "AI"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("is_internal", models.BooleanField(default=False)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "support_ticket_message",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="supportchannel",
            index=models.Index(
                fields=["organization", "type"], name="support_cha_organiz_3d1d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "status"], name="support_tic_organiz_153649_idx"
            ),
        ),
    ]
