# Generated by Django 5.1.15 on 2026-07-12 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflow",
            new_name="workflows_w_organiz_867754_idx",
            old_name="workflows_w_organiz_7f0c5a_idx",
        ),
    ]
