# Generated by Django 5.1.15 on 2026-07-12 18:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "organizations",
            "0003_rename_organizatio_organiz_7f2a1c_idx_organizatio_organiz_a8ab14_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("buffer_minutes", models.PositiveIntegerField(default=0)),
                ("availability", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_links",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meetings_booking_link",
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("microsoft", "Microsoft")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("access_token", models.CharField(blank=True, default="", max_length=1024)),
                ("refresh_token", models.CharField(blank=True, default="", max_length=1024)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meetings_calendar_connection",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("location", models.CharField(blank=True, default="", max_length=512)),
                ("meeting_url", models.URLField(blank=True, default="")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("zoom", "Zoom"),
                            ("google_meet", "Google Meet"),
                            ("teams", "Microsoft Teams"),
                            ("in_person", "In Person"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=32,
                    ),
                ),
                ("attendees", models.JSONField(blank=True, default=list)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meetings_meeting",
                "ordering": ("-starts_at",),
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invitee_name", models.CharField(max_length=255)),
                ("invitee_email", models.EmailField(max_length=254)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="confirmed",
                        max_length=32,
                    ),
                ),
                (
                    "booking_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="meetings.bookinglink",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meetings_booking",
                "ordering": ("-starts_at",),
            },
        ),
        migrations.CreateModel(
            name="MeetingReminder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("remind_at", models.DateTimeField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("in_app", "In App")],
                        default="email",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meetings_reminder",
                "ordering": ("remind_at",),
            },
        ),
        migrations.AddIndex(
            model_name="bookinglink",
            index=models.Index(
                fields=["organization", "is_active"], name="meetings_bo_organiz_8afd3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarconnection",
            index=models.Index(
                fields=["organization", "provider"], name="meetings_ca_organiz_ab4098_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organization", "status"], name="meetings_me_organiz_5cee97_idx"
            ),
        ),
    ]
