# Generated by Django 5.1.15 on 2026-07-12 18:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "organizations",
            "0003_rename_organizatio_organiz_7f2a1c_idx_organizatio_organiz_a8ab14_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("marketing", "Marketing"),
                            ("hr", "HR"),
                            ("finance", "Finance"),
                            ("legal", "Legal"),
                            ("research", "Research"),
                            ("support", "Support"),
                            ("executive", "Executive"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("tools", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent",
                "ordering": ("type", "name"),
            },
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.JSONField(blank=True, default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_memory",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("input", models.TextField()),
                ("output", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("citations", models.JSONField(blank=True, default=list)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="agents.agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_run",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["organization", "type"], name="agents_agen_organiz_242b70_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentmemory",
            unique_together={("agent", "key")},
        ),
    ]
